In [1]:
import numpy as np

In [2]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(mat.ndim)
print(mat.shape)

2
(3, 3)


In [3]:
arr = np.array([1,5,9])

print(arr.ndim)
print(arr.shape)

1
(3,)


In [4]:
arr = np.array([[1,2,3],
                [4,'5',6],
                [7,8,9]])

print(arr.dtype)
arr2 = arr.astype(float)
print(arr2.dtype)
print(arr2)

<U21
float64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
np.savez("first.npz")

In [7]:
arr =  np.array([1,2,3,4,5,7])
new = arr.reshape(3,2)

print(arr)
print(new)
print(arr.shape)
print(new.shape)

[1 2 3 4 5 7]
[[1 2]
 [3 4]
 [5 7]]
(6,)
(3, 2)


In [8]:
vec = np.array([1,2,3,5,8,9])
mat = vec.reshape((vec.shape[0],1))

print(vec)
print(vec.dtype)
print(mat)
print(mat.dtype)

[1 2 3 5 8 9]
int64
[[1]
 [2]
 [3]
 [5]
 [8]
 [9]]
int64


In [15]:
vec = np.array([1,10,80,90,55852])
mat = vec.reshape(-10,1)

print(vec)
print(mat)

[    1    10    80    90 55852]
[[    1]
 [   10]
 [   80]
 [   90]
 [55852]]


In [ ]:
arr = np.array([[1,2,3],
                [4,2,6],
                [7,8,9],
                [0,0,0]])

print(arr[2,1])

8


In [21]:
arr = np.array([[1,2,3],
                [4,2,6],
                [7,8,9],
                [0,0,0]])

print(arr[0:3])

[[1 2 3]
 [4 2 6]
 [7 8 9]]


In [23]:
arr = np.array([[1,2,3],
                [4,2,6],
                [7,8,9]])

arr3 = arr.T
print(arr3)


[[1 4 7]
 [2 2 8]
 [3 6 9]]


In [ ]:
arr = np.empty((3,3))

print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 9.9e-324 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


: 